name: taxi_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  pin_code_fields: ^8.0.0
  google_maps_flutter: ^2.5.0
  lucide_icons: ^0.257.0
  camera: ^0.11.1
  permission_handler: ^11.4.0
  google_mlkit_face_detection: ^0.12.0
  share_plus: ^10.1.4
  flutter_facebook_auth: ^6.0.2
  mongo_dart: ^0.10.4
  http: ^1.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  country_picker: ^2.0.20
  # firebase_core: ^2.0.0
  # firebase_auth: ^3.3.4

flutter:
  uses-material-design: true
  assets:
    - assets/image-removebg-preview.png
    - assets/image-removebg-preview1.png
    - assets/image-removebg-preview2.png
    - assets/image-removebg-preview3.png
    - assets/image-removebg-preview4.png
    - assets/image-removebg-preview5.png

